### ISSUE TITLE
pocof crash with the error message `Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.`

### ISSUE THREAD

**Issue by krymtkts** [krymtkts/pocof#158]
The detailed error message with `$ErrorView = 'detail'` is following.

```
Exception             :
    Type       : System.InvalidOperationException
    TargetSite :
        Name          : ReadKey
        DeclaringType : System.ConsolePal, System.Console, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
        MemberType    : Method
        Module        : System.Console.dll
    Message    : Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
    Source     : System.Console
    HResult    : -2146233079
    StackTrace :
   at System.ConsolePal.ReadKey(Boolean intercept)
   at Pocof.Screen.RawUI.Pocof.Screen.IRawUI.ReadKey(Boolean intercept) in C:\Users\takatoshi\dev\github.com\krymtkts\pocof\src\pocof\Screen.fs:line 41
   at Pocof.Screen.Buff.read(FSharpList`1 acc) in C:\Users\takatoshi\dev\github.com\krymtkts\pocof\src\pocof\Screen.fs:line 161
   at Pocof.Screen.Pipe #1 input at line 283@283.Invoke(Tuple`3 tupledArg) in C:\Users\takatoshi\dev\github.com\krymtkts\pocof\src\pocof\Screen.fs:line 283
   at <StartupCode$FSharp-Core>.$Async.FromContinuations@1449.Invoke(AsyncActivation`1 ctxt) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1470
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1139
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Pocof.Screen.Buff.GetKey() in C:\Users\takatoshi\dev\github.com\krymtkts\pocof\src\pocof\Screen.fs:line 284
   at Pocof.Pocof.args@154-1.Invoke(Unit unitVar)
   at Pocof.Pocof.loop(LoopFixedArguments args, FSharpList`1 results, InternalState state, Position pos, QueryContext context) in C:\Users\takatoshi\dev\github.com\krymtkts\pocof\src\pocof\Pocof.fs:line 118
   at Pocof.Pocof.interact(InternalConfig conf, InternalState state, Position pos, FSharpFunc`2 rui, FSharpFunc`2 invoke, FSharpList`1 input) in C:\Users\takatoshi\dev\github.com\krymtkts\pocof\src\pocof\Pocof.fs:line 158
   at Pocof.SelectPocofCommand.EndProcessing() in C:\Users\takatoshi\dev\github.com\krymtkts\pocof\src\pocof\Library.fs:line 98
   at System.Management.Automation.CommandProcessorBase.Complete()
CategoryInfo          : NotSpecified: (:) [Select-Pocof], InvalidOperationException
FullyQualifiedErrorId : System.InvalidOperationException,Pocof.SelectPocofCommand
InvocationInfo        :
    MyCommand        : Select-Pocof
    ScriptLineNumber : 1
    OffsetInLine     : 6
    HistoryId        : 8
    Line             : ll | pocof
    Statement        : pocof
    PositionMessage  : At line:1 char:6
                       + ll | pocof
                       +      ~~~~~
    InvocationName   : pocof
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

This error seems to be related to typing `Ctrl+S` twice, and it doesn't appear to be related to PSReadLine. I remove the shortcut key `Ctrl+S` for the `ForwardSearchHistory` function and tested it, and no error occurred.

It occurs when I use the Windows Terminal (Preview), but no error occurs when I use the VS Code terminal.

**Comment by krymtkts** [comment]
This error seems to be caused by the `Ctrl+S` pause.
